name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: gonzolino/ocm-test
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          regitry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
