name: OCM Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: OCM Release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: open-component-model/ocm-setup-action@30210abb7373f34003cd50cdab77e23497afa6a7
      - run: ocm --version # debug
      - run: ocm add components --create --file ocm/ctf ocm/component-constructor.yaml VERSION=${{ github.event.release.tag_name }}
      - run: ocm transfer ctf ocm/ctf ghcr.io/gonzolino/ocm
